---
language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - cd SynchronizedList
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - dev
